### PR TITLE
Add -race testflag in make targets

### PR DESCRIPTION
**Pull request by fangxlmr**
-race flag would help to avoid data race issue in go codebase.

### CODE REVIEW

**Comment by fangxlmr** [comment]
1. Actually, there is no `dev` branch so I've got to send a PR to `master`. Recommand to create one.
2. The Makefile is not right :(

**Comment by fangxlmr** [comment]
Ah, notice that the Makefile target `rzpm` is renamed to `rz-pm` in unmerged #5. :)

**Comment by XVilka** [comment]
@fangxlmr yes, I think @ret2libc had something in mind to finish before merging that PR.

**Review by wargio — APPROVED** [review]

**Comment by ret2libc** [comment]
Closing this as I essentially restarted the project.

**Pull request closed without merging**
